language: node_js
node_js:
  - '8'
  - '10'

env:
  global:
    - GH_REF=git@github.com:kamataryo/jqf.git

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - npm test

after_success:
  - test "$TRAVIS_BRANCH" != 'master' && exit 0
  - test "$TRAVIS_NODE_VERSION" != '10' && exit 0
  - openssl aes-256-cbc -K $encrypted_04592acae1fe_key -iv $encrypted_04592acae1fe_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - git config --global user.name "travis"
  - git config --global user.email "tarvis@kamataryo.com"
  - cd website
  - yarn install
  - npm run build
  - cd build
  - git init
  - git checkout -b gh-pages
  - git add .
  - git commit -m"[skip ci] Deploy from travis"
  - git remote add origin $GH_REF
  - git push -f origin gh-pages

deploy:
  provider: script
  script: echo "//registry.npmjs.org/:_authToken=${API_TOKEN}" > $HOME/.npmrc && npm publish --access=public
  on:
    tags: true
    condition: '$TRAVIS_NODE_VERSION = 10'
  skip_cleanup: true

notifications:
  email: false
