language: node_js
node_js:
  - '8'
  - '10'

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - npm test

after_success:
  - openssl aes-256-cbc -K $encrypted_04592acae1fe_key -iv $encrypted_04592acae1fe_iv -in .travis_rsa.enc -out ./.travis_rsa -d
  - mv ./.travis_rsa $HOME/.ssh/id_rsa && chmod 600 $HOME/.ssh/id_rsa
  - git config --global user.name "travis"
  - git config --global user.email "tarvis@kamataryo.com"
  - test "$TRAVIS_BRANCH" = 'master' && cd website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages

deploy:
  provider: script
  script: echo "//registry.npmjs.org/:_authToken=${API_TOKEN}" > $HOME/.npmrc && npm publish --access=public
  on:
    tags: true
    condition: '$TRAVIS_NODE_VERSION = 10'
  skip_cleanup: true

notifications:
  email: false
