# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun test
      - run: bun run build
      - run: pushd website && bun install && bun run build && popd

      - name: save the built
        uses: actions/upload-artifact@v4
        with:
          name: the-built
          path: |
            dist/
            docs/

  publish:
    name: 'Publish npm package'
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'

      - name: load the built
        uses: actions/download-artifact@v4
        with:
          name: the-built

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.API_TOKEN }}


